#!/bin/sh

COMPILE='i386--mingw32-gcc -DHAVE_CONFIG_H -I. -I. -I.. -I../jnlib
 -I../intl -mdll -g -I/home/wk/work/gtk+w32/include/gtk+/gdk/win32
 -I/home/wk/work/gtk+w32/include -I/home/wk/work/gtk+w32/include/gtk+
 -Wall -Wcast-align -Wstrict-prototypes -c'

SRCS='
gpapa.c
gpapafile.c
gpapaintern.c
gpapakey.c
gpapapublickey.c
gpapasecretkey.c
gpapasignature.c
'

OBJS=
for i in $SRCS; do
   o="`basename $i .c`.o"
   if [ ! -f $o -o $i -nt $o ]; then
       echo "compiling $i" >&2
       $COMPILE $i || exit 1
   fi
   OBJS="$OBJS $o"
done

echo 'running dlltool the first time' >&2
dlltool --nodelete --as i386--mingw32-as --def gpapa.def --output-exp gpapa.exp \
	--output-lib gpapa.imp --dllname gpapa.dll $OBJS
echo 'doing dummy link to create the base file' >&2
i386--mingw32-gcc -v -mdll -Wl,--base-file -Wl,gpapa.base \
   -o gpapa.dll gpapa.exp $OBJS \
  -L ../jnlib -ljnlib -L/home/wk/work/gtk+w32/lib -lgtk -lgdk -lglib

echo 'running dlltool the second time' >&2
dlltool --nodelete --as i386--mingw32-as --def gpapa.def --output-exp gpapa.exp \
        --output-lib gpapa.imp --base-file gpapa.base --dllname gpapa.dll $OBJS

echo 'doing final link' >&2
i386--mingw32-gcc -v -mdll -o gpapa.dll gpapa.exp $OBJS \
    -L ../jnlib -ljnlib -L/home/wk/work/gtk+w32/lib -lgtk -lgdk -lglib


